name: llm_agents
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.16=h02f6b3c_0
  - pip=25.0=py311hca03da5_0
  - python=3.11.11=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=75.8.0=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - accelerate==1.11.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.69.0
      - anyio==4.9.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - authlib==1.6.0
      - babel==2.17.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - browser-use==0.7.10
      - bubus==1.5.6
      - cdp-use==1.4.1
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.2.1
      - comm==0.2.2
      - contourpy==1.3.3
      - cryptography==45.0.4
      - cycler==0.12.1
      - cython==3.1.4
      - dataclasses-json==0.6.7
      - datasets==4.4.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - faiss-cpu==1.12.0
      - fastapi==0.121.2
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.4.0
      - fastar==0.6.0
      - fastjsonschema==2.21.1
      - fastmcp==2.8.1
      - ffmpy==0.6.0
      - filelock==3.18.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - google-api-core==2.25.1
      - google-api-python-client==2.183.0
      - google-auth==2.41.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - google-genai==1.39.1
      - gradio==5.34.2
      - gradio-client==1.10.3
      - greenlet==3.2.4
      - groovy==0.1.2
      - groq==0.32.0
      - h11==0.14.0
      - hf-xet==1.1.4
      - html2text==2025.4.15
      - httpcore==1.0.7
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface==0.0.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.5.2
      - json5==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.9
      - langchain==1.1.2
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.1.1
      - langchain-huggingface==1.1.0
      - langchain-mcp-adapters==0.1.14
      - langchain-ollama==1.0.0
      - langchain-openai==1.1.0
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.4
      - langgraph-checkpoint==2.1.0
      - langgraph-prebuilt==1.0.4
      - langgraph-sdk==0.2.6
      - langsmith==0.4.4
      - markdown==3.10
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mcp==1.13.1
      - mdurl==0.1.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - multidict==6.3.2
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - narwhals==2.13.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook-shim==0.2.4
      - numpy==2.2.4
      - oauthlib==3.3.1
      - ollama==0.6.1
      - openai==1.109.1
      - openapi-pydantic==0.5.1
      - orjson==3.10.16
      - ormsgpack==1.10.0
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - playwright==1.55.0
      - plotly==6.5.0
      - portalocker==2.10.1
      - posthog==6.7.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==6.32.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycparser==2.22
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydub==0.25.1
      - pyee==13.0.0
      - pygments==2.19.1
      - pyobjc-core==11.1
      - pyobjc-framework-cocoa==11.1
      - pyotp==2.9.0
      - pyparsing==3.2.5
      - pypdf==6.1.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - regex==2024.11.6
      - reportlab==4.4.4
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rich-toolkit==0.15.1
      - rignore==0.7.6
      - rpds-py==0.24.0
      - ruff==0.12.0
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.1
      - screeninfo==0.8.1
      - selenium==4.35.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.45.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==2.0.40
      - sse-starlette==2.3.6
      - stack-data==0.6.3
      - starlette==0.46.2
      - sympy==1.14.0
      - tenacity==9.1.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.22.0
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.9.1
      - torchvision==0.24.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.56.1
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uuid-utils==0.12.0
      - uuid7==0.1.0
      - uvicorn==0.34.3
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.13
      - wikipedia==1.4.0
      - wsproto==1.2.0
      - xxhash==3.5.0
      - yarl==1.18.3
      - zstandard==0.23.0
prefix: /Users/skaltenp/anaconda3/envs/llm_agents
